name = "pointless_scheme"
version = "0.1.0"
defaultTargets = ["pointless_scheme"]

[[lean_lib]]
name = "PointlessScheme"

[[lean_exe]]
name = "pointless_scheme"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
