name = "PointlessScheme"
version = "0.1.0"
defaultTargets = ["PointlessScheme"]

[[lean_lib]]
name = "PointlessScheme"

[[require]]
name = "mathlib"
git = "https://github.com/frenzymath/mathlib4.git"
rev = "reap"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
