name = "pointless_scheme"
version = "0.1.0"
defaultTargets = ["PointlessScheme"]

[[lean_lib]]
name = "PointlessScheme"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"